#!/usr/bin/env zsh
# shellcheck shell=bash
# Write your bootstrap code here

# Set the ZUnit directory
export ZUNIT_DIR
ZUNIT_DIR="$(cd "$(dirname "${0}")/.." && pwd)"


# Set the minidocs variable for direct use in tests
export minidocs
minidocs="$(cd "$(dirname "${0}")/../.." && pwd)/minidocs"

# Ensure the script is executable
chmod +x "${minidocs}"

# Print the path to verify
echo "minidocs: ${minidocs}"
echo "ZUNIT_DIR: ${ZUNIT_DIR}"
