name: ZUnit Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  setup:
    uses: ./.github/workflows/base-setup.yml

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run ZUnit tests
        run: |
          # Run ZUnit tests from the repository directory
          # Make sure the minidocs script is executable
          chmod +x ./minidocs
          zunit run
